// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6G8xRwn8CsN03FL908x1wsZA2CI6prtk',
    appId: '1:142023273276:web:f1fa2c5d77b82369110c39',
    messagingSenderId: '142023273276',
    projectId: 'moje-faktury-developement',
    authDomain: 'moje-faktury-developement.firebaseapp.com',
    storageBucket: 'moje-faktury-developement.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOZUTKELKBro4QTbc2mzzQURinmmYM2X0',
    appId: '1:142023273276:android:883fcda615122548110c39',
    messagingSenderId: '142023273276',
    projectId: 'moje-faktury-developement',
    storageBucket: 'moje-faktury-developement.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRypgB6t95PPz74TOpQ3WHVLjNp5UT7GY',
    appId: '1:142023273276:ios:c137924b9e878282110c39',
    messagingSenderId: '142023273276',
    projectId: 'moje-faktury-developement',
    storageBucket: 'moje-faktury-developement.appspot.com',
    iosClientId: '142023273276-chil2nu9c5mqd2uas4nupcg1io3s5450.apps.googleusercontent.com',
    iosBundleId: 'com.filipdoganowski.mojeFaktury',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRypgB6t95PPz74TOpQ3WHVLjNp5UT7GY',
    appId: '1:142023273276:ios:c137924b9e878282110c39',
    messagingSenderId: '142023273276',
    projectId: 'moje-faktury-developement',
    storageBucket: 'moje-faktury-developement.appspot.com',
    iosClientId: '142023273276-chil2nu9c5mqd2uas4nupcg1io3s5450.apps.googleusercontent.com',
    iosBundleId: 'com.filipdoganowski.mojeFaktury',
  );
}
